import fs from 'node:fs/promises';
import {Presentation,PresentationFile} from '@oai/artifact-tool';
import {resolvePresentationFont,applyPresentationChartFont,finalizePresentation} from 'file:///C:/Users/User/.codex/plugins/cache/openai-primary-runtime/presentations/26.909.11814/skills/presentations/container_tools/artifact_tool_utils.mjs';
const root=process.cwd().replaceAll('\\','/'), tmp=root+'/tmp/defense-deck';
const d=JSON.parse(await fs.readFile(tmp+'/data.json','utf8'));
const font=resolvePresentationFont({fontFamily:'Arial'});
const p=Presentation.create({slideSize:{width:1280,height:720}}), outline=[], chartOwners=[];
const green='#234F3A',ink='#192D24',muted='#516359',bg='#F7F8F2';
function text(s,t,x,y,w,h,size=28,color=ink,bold=false){const a=s.shapes.add({geometry:'textbox',position:{left:x,top:y,width:w,height:h},fill:'none',line:{fill:'none',width:0}});a.text=t;a.text.style={typeface:font,fontSize:size,color,bold,autoFit:'none'};return a;}
function slide(title,note='',dark=false){const s=p.slides.add();s.background.fill=dark?green:bg;text(s,title,65,48,1148,170,42,dark?'#FFFFFF':ink,true);text(s,String(p.slides.items.length).padStart(2,'0'),1170,665,50,28,17,dark?'#D6E4D4':muted);s.speakerNotes.textFrame.setText(note);outline.push({title,notes:note});return s;}
function body(title,lines,note='',dark=false){const s=slide(title,note,dark);lines.forEach((line,i)=>text(s,line,68,194+i*98,1130,86,29,dark?'#EFF5EB':ink));return s;}
const order=['DecisionTree','RandomForest','XGBoost','SoftVoting','ShallowMLP','DeepMLP','FeatureCNN'];
const labels=['Decision tree','Random forest','XGBoost','Soft voting','Shallow MLP','Deep MLP','Feature CNN'];
function chart(title,cats,values,foot,note,{max=1,min=0,color=green,name='Score'}={}){const s=slide(title,note);const c=s.charts.add('bar',{position:{left:66,top:175,width:1145,height:390},categories:cats,series:[{name,values:values.map(v=>Number(v.toFixed(6))),fill:color,valuesFormatCode:max===80?'0':'0.000'}],barOptions:{direction:'column',grouping:'clustered',gapWidth:100},hasLegend:false,xAxis:{tickLabelPosition:'low',textStyle:{fontSize:22,fill:ink},majorGridlines:null},yAxis:{min,max,numberFormatCode:'0.0',textStyle:{fontSize:20,fill:muted}},dataLabels:{showValue:true,position:'outEnd',textStyle:{fontSize:21,fill:ink}},chartFill:bg,plotAreaFill:bg});applyPresentationChartFont(c,{fontFamily:font});text(s,foot,70,599,1110,62,22,muted);chartOwners.push(p.slides.items.length);return s;}
function detection(source,target,task,title,foot){let rows=order.map(m=>d.detection.find(r=>r.source===source&&r.target===target&&r.task===task&&r.model===m));chart(title,labels,rows.map(r=>+r.macro_f1_mean),foot,'Source: results/study/across_seed_summary.csv. Mean across seeds 7, 42, 1337. Individual SD values: '+rows.map(r=>r.model+' '+r.macro_f1_sd).join('; ')+'. Chart shows means only. Full report contains separate SD figures. Same feature-group protocol across models.');}
let s=slide('Evaluating the Reliability of\nExplainable AI in Ensemble-Based\nIntrusion Detection Systems','Original title and authors from thesis/reference/original_thesis.docx. Expanded work includes neural baselines, transfer and LLMs.',true);
text(s,'THESIS DEFENSE',70,237,1100,40,22,'#CFE0C9');
text(s,'Mehedi Hasan (C213061)\nSazzadul Islam (C213066R)',70,327,1100,95,30,'#FFFFFF');
text(s,'Supervisor: Mr. Md. Mahiuddin, Associate Professor\nDepartment of CSE\nInternational Islamic University Chittagong',70,483,1110,132,24,'#DCE9D8');
body('The research problem',['An accurate detector can still produce unreliable explanations.','Repeated rankings may look consistent while masking tests show little predictive relevance.','A new traffic domain can change both detection and explanation behavior.'],'Source: preserved thesis, expanded introduction and results. Predictive relevance refers to a masking proxy, not causal truth.');
body('Research questions',['RQ1  How repeatable are local explanations?','RQ2  How faithful are they under controlled masking tests?','RQ3  How do detection and explanations transfer?','RQ4  How much do independent explainers agree?'],'Original RQ numbering preserved. RQ4 is historical LIME/TreeSHAP agreement. The LLM classification and explanation study is a separate extension.');
body('Research gap and contribution',['Evaluate explanation reliability separately from detection accuracy.','Compare repeatability with a matched random masking control.','Test frozen detectors on a second dataset and include neural models.','Report LLM classification failures and explanation coverage.'],'Scope of this study, not an exhaustive claim of novelty. Do not claim the first systematic study. The unverified historical reference [28] is not used to substantiate novelty.');
body('Datasets and shared representation',['NF-UNSW-NB15-v2: 1,986,745 cleaned flows.','NF-CSE-CIC-IDS2018-v2: 17,129,715 cleaned flows.','39 shared numeric features after removing identifiers and targets.','Binary transfer uses compatible labels. Multiclass evaluation stays within each dataset.'],'Source: thesis/manuscript.md, expanded methods. Cleaned release sizes differ from per-fit sampling caps. Attack taxonomies are not assumed equivalent.');
body('Evaluation protocol',['Group identical feature vectors before the 70/15/15 split.','Cap training at 200,000 flows, validation at 40,000 and test at 80,000.','Repeat detector fitting with seeds 7, 42 and 1337.','Freeze preprocessing and the source model for target evaluation.'],'Source: expanded methods. Signed-log float32 representation and consistent global feature-group hashing. No chronological split. Caps apply per dataset and seed, not the full release.');
body('Model comparison',['Tree models: decision tree, random forest and XGBoost.','Ensemble: soft voting over the three tree models.','Neural models: shallow MLP, deep MLP and feature-axis CNN.','84 fitted configurations and 126 evaluation cells.'],'Seven families x two datasets x two tasks x three seeds = 84 fits. Binary models evaluate both domains and native multiclass models evaluate their own domain. Feature CNN convolves tabular feature positions, not time.');
body('Explanation evaluation',['LIME: 20 balanced unique feature groups per domain.','Three explainer seeds and 5,000 perturbations per explanation.','Jaccard@5 measures overlap between repeated feature sets.','Masking advantage compares selected features with random masks.'],'Source: results/study/xai/aggregate.csv and expanded methods. 14 binary models at training seed 42 x two domains. Fix the original predicted class. Median masking, absolute feature ranking, k=1..5. Bootstrap intervals use 5,000 stratified resamples conditional on the fitted model.');
detection('unsw','unsw','binary','Binary detection on UNSW','Macro-F1 means across three seeds. XGBoost leads at 0.9750.');
detection('ids2018','ids2018','binary','Binary detection on IDS2018','Macro-F1 means across three seeds. Random forest leads at 0.9852.');
detection('unsw','ids2018','binary','Transfer from UNSW to IDS2018','Frozen binary models. All seven families deteriorate on the target domain.');
detection('ids2018','unsw','binary','Transfer from IDS2018 to UNSW','Macro-F1 means across three seeds. The best target mean remains about 0.516.');
let xr=order.map(m=>d.xai.find(r=>r.source==='unsw'&&r.target==='ids2018'&&r.model===m));
chart('Explanation stability after transfer',labels,xr.map(r=>+r.jaccard5_mean),'UNSW-trained models on IDS2018. Random forest Jaccard@5 = 0.9222.','Source: results/study/xai/aggregate.csv. Twenty balanced cases, three explainer seeds, training seed 42. Stability describes repeatability only.',{name:'Jaccard@5'});
chart('Masking advantage after transfer',labels,xr.map(r=>+r.advantage_mean),'Random forest: -0.1338, 95% interval [-0.2034, -0.0476].','Source: results/study/xai/aggregate.csv. Positive advantage means greater fixed-class probability removal than matched random masks. Intervals conditional on one fit and 20 cases. Values do not establish causal feature importance.',{min:-0.25,max:.8,name:'Masking advantage'});
body('Stability does not establish faithfulness',['Random forest remains highly repeatable after transfer.','Its median-mask advantage becomes negative on IDS2018.','Signed ranking and mean masking can change the result.','Interpret the score together with its perturbation protocol.'],'RF UNSW to IDS2018: median absolute -0.1338, mean absolute -0.1247, median signed 0.0795, mean signed 0.2215. Source: expanded masking sensitivity section. 112 summary cells, 2,240 cases. Out-of-distribution perturbations remain a limitation.');
body('Historical result audit',['483 matched cases per tree model support reconstruction.','Within-model stability–advantage correlations are positive.','The arithmetic reconstruction found no material reversal.','The old random split has 88.97% exact-input overlap.'],'Source: results/study/audit and preserved report historical audit. Spearman correlations: DT .203684, RF .208214, XGB .258441. Maximum aggregate error 5.17e-7. Unmasked replay error 4.44e-16. Exact historical masks cannot be replayed because rankings were not saved. Overlap limits generalization claims. An inverse aggregate ordering alone is not evidence of fabricated results.');
body('RQ4: agreement between explainers',['Historical LIME and TreeSHAP rankings show partial agreement.','Random forest rank correlation is 0.676 in that protocol.','The same comparison shares only two of the top five features.','Rank correlation and top-feature overlap answer different questions.'],'Source: original thesis RQ4 results, preserved report. Historical protocol only. Do not generalize these values to the expanded neural fits or target-domain experiments. No new neural SHAP or TOPSIS evaluation is claimed.');
body('Language-model extension',['Qwen2.5-0.5B, TinyLlama-1.1B and SmolLM2-1.7B.','400 classification cases per model under the frozen prompt.','80 own-decision and 80 detector-grounded explanations per model.','1,200 classifications and 240 matched explanation pairs.'],'Source: results/study/llm and expanded LLM methods. Local instruction models, four-example prompt, constrained classification scoring. CPU float32, two threads, maximum 192 generated tokens for explanations.');
chart('LLM classification under the frozen prompt',['Qwen2.5','TinyLlama','SmolLM2'],[1/3,1/3,1/3],'Each model predicts one class throughout its balanced cohort. Balanced accuracy = 0.5000.','Source: expanded LLM results. Qwen and Smol predict Benign throughout, TinyLlama predicts Attack. Macro-F1 1/3. This is a result for this prompt, scoring procedure and these small models, not every LLM.',{name:'Macro-F1'});
const llms=['Qwen','TinyLlama','SmolLM2'];
for(const kind of ['own','detector']) {const vals=llms.map(m=>d.llm.filter(r=>r.model.includes(m)&&r.kind===kind).reduce((a,r)=>a+(+r.valid),0));chart(kind==='own'?'Valid own-decision explanations':'Valid detector-grounded explanations',llms,vals,'Valid feature-list outputs out of 80 per model. Masking scores apply only to valid outputs.','Source: results/study/llm/masking_coverage.csv. Validity requires usable feature selections under the saved protocol. Conditional masking performance cannot substitute for coverage.',{max:80,name:'Valid outputs'});}
body('Conclusions',['High within-dataset accuracy does not guarantee transfer.','Stable explanations can have weak masking advantage.','The small LLMs fail classification under the tested protocol.','The audit supports narrower, protocol-specific conclusions.'],'Answer RQ1–RQ3 using the expanded evidence and RQ4 using historical agreement. Explain that a masking proxy cannot prove causal faithfulness. Avoid treating seed-42 case intervals as uncertainty across training runs.',true);
body('Limitations and future work',['Use chronological splits and evaluate on operational traffic.','Repeat explanation tests across more cases and training seeds.','Test conditional perturbations and analyst usefulness.','Evaluate larger LLMs with controlled prompt and scoring ablations.'],'Remaining scope includes per-attack-class explanation rank drift, expanded explainer comparisons, and realistic deployment validation. No causal ground truth or analyst study in this thesis.');
body('Questions',['How should explanation reliability change an IDS decision?','Backup slides contain multiclass results and protocol details.'],'Discussion. Main defense ends here. The following slides support examiner questions.',true);
detection('unsw','unsw','multiclass','Backup: UNSW multiclass detection','Native attack taxonomy. Macro-F1 means across three seeds.');
detection('ids2018','ids2018','multiclass','Backup: IDS2018 multiclass detection','Native attack taxonomy. Cross-dataset multiclass labels are not aligned.');
body('Backup: neural training protocol',['Shallow MLP: one hidden layer with 64 units.','Deep MLP: 256, 128 and 64 units with 0.1 dropout.','Feature CNN: 16 and 32 channels, kernel size 3, dense layer 64.','AdamW, 20-epoch cap, patience 4, batch size 1,024.'],'Source: expanded methods. Learning rate .001, weight decay .0001, class-weighted cross entropy, early stopping on unweighted source validation loss. The CNN is not a temporal model.');
body('Backup: sources and evidence',['Original thesis and preserved expanded report.','Detection: results/study/across_seed_summary.csv','Explanations: results/study/xai/aggregate.csv','LLM coverage: results/study/llm/masking_coverage.csv'],'Primary project sources: thesis/reference/original_thesis.docx; output/pdf/thesis_xai_ids_preserved.pdf; thesis/manuscript.md (expanded numerical narrative only, original RQ4 numbering retained in deck). Complete bibliography in preserved report. Historical reference [28] remains unverified and supports no presentation claim. Repository: https://github.com/mehedihasan722/Thesis-Defense-Project-XAI-ids-Update');
await fs.writeFile(tmp+'/outline.json',JSON.stringify(outline,null,2));
await (await PresentationFile.exportPptx(p)).save(tmp+'/candidate.pptx');
for(let i=0;i<p.slides.items.length;i++){const b=await p.export({slide:p.slides.items[i],format:'png',scale:1});await fs.writeFile(tmp+`/slide-${String(i+1).padStart(2,'0')}.png`,new Uint8Array(await b.arrayBuffer()));}
const skill='C:/Users/User/.codex/plugins/cache/openai-primary-runtime/presentations/26.909.11814/skills/presentations';
console.log(await finalizePresentation({workspaceDir:root,candidatePath:tmp+'/candidate.pptx',finalPath:root+'/output/presentation/thesis_defense_v2.pptx',pythonExecutable:'C:/Users/User/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/python.exe',integrityValidatorPath:skill+'/container_tools/inspect_presentation_package_integrity.py',layoutValidatorPath:skill+'/container_tools/inspect_presentation_layout_geometry.py',layoutArgs:['--expected-slide-size-emu','12192000,6858000','--validate-heading-fit'],requiredNativeChartOwnerSlides:chartOwners,materializeLiteralChartWorkbooks:true,fontPolicy:{basis:'design',families:[font]},verifyArtifactToolImport:true,receiptPath:tmp+'/validation-v2.json'}));
console.log('SLIDES',p.slides.items.length);




